# Generated by Django 5.1.5 on 2025-01-22 12:28

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.accounts.models.image_directory),
        ),
    ]
