# Generated by Django 5.1.5 on 2025-01-19 20:47

import django.db.models.deletion
import uuid_extensions.uuid7
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.UUIDField(default=uuid_extensions.uuid7, editable=False, primary_key=True, serialize=False)),
                ('internship_type', models.CharField(choices=[('industrial_training', 'Industrial Training'), ('nysc', 'NYSC'), ('volunteering', 'Volunteering')], db_index=True, max_length=120)),
                ('department', models.CharField(choices=[('oil_and_gas', 'Oil and Gas Department'), ('solid_minerals', 'Solid Minerals Department'), ('geological_services', 'Geological Services Department'), ('power', 'Power Department'), ('procurement', 'Procurement Department'), ('admin_hr', 'Admin and HR'), ('accounts', 'Accounts Department'), ('public_relations', 'Public Relations Unit'), ('ps_office', "Permanent Secretary's Office")], db_index=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('internship_start_date', models.DateField(db_index=True)),
                ('internship_end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('internship_duration', models.DurationField(db_index=True)),
                ('date_joined', models.DateField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intern',
                'verbose_name_plural': 'Interns',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.DeleteModel(
            name='Intern',
        ),
    ]
