# Generated by Django 5.1.5 on 2025-01-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_internship_delete_intern'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Internship', 'verbose_name_plural': 'Internships'},
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='internship_start_date',
            new_name='start_date',
        ),
    ]
